import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/ai-calc.ts",
    "src/auth.ts",
    "src/catalog.ts",
    "src/contracts.ts",
    "src/diario.ts",
    "src/documents.ts",
    "src/equipe.ts",
    "src/geo.ts",
    "src/legal.ts",
    "src/material-lists.ts",
    "src/media.ts",
    "src/milestones.ts",
    "src/painel-financeiro.ts",
    "src/portfolio.ts",
    "src/profile.ts",
    "src/public-profiles.ts",
    "src/purchase-orders.ts",
    "src/purchase-quotes.ts",
    "src/rfq.ts",
    "src/reviews.ts",
    "src/rfq-proposals.ts",
    "src/search.ts",
    "src/works.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  clean: true,
  sourcemap: true,
});
